on: 
  push:
    branches:
      - main

env:
  MELTANO_CLI_LOG_LEVEL: info
  TARGET_BIGQUERY_LOCATION: us-west1
  TARGET_BIGQUERY_DATASET_ID: bronze

jobs:

  deploy-staging:
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://console.cloud.google.com/bigquery
    env:
      MELTANO_ENVIRONMENT: staging
      TARGET_BIGQUERY_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      
    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create client_secrets.json from GHA secret
        run: |
          echo "$GCP_KEY" > client_secrets.json
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}
        
      - name: Install Meltano and run
        run: |
          pipx install meltano[gcs]
          meltano install
          meltano config tap-csv test
          meltano run tap-csv target-bigquery


  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   needs: deploy-staging
  #   environment: 
  #     name: prod
  #     url: https://console.cloud.google.com/bigquery
  #   env:
  #     MELTANO_ENVIRONMENT: prod
  #     GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  #   steps:
  #     - run: echo deploying to prod with ${{ secrets.SECRET }}
