on: 
  push:
    branches:
      - main

jobs:

  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - run: echo hi


  deploy-staging:
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://console.cloud.google.com/bigquery
    steps:
      - run: echo deploying to staging with ${{ secrets.SECRET }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: 
      name: prod
      url: https://console.cloud.google.com/bigquery
    steps:
      - run: echo deploying to prod with ${{ secrets.SECRET }}